export const GET_CONVERSATIONS_REQUEST = "GET_CONVERSATIONS_REQUEST"
export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS"
export const GET_CONVERSATIONS_FAIL = "GET_CONVERSATIONS_FAIL"

export const SEEN_CONVERSATIONS_REQUEST = "SEEN_CONVERSATIONS_REQUEST"
export const SEEN_CONVERSATIONS_SUCCESS = "SEEN_CONVERSATIONS_SUCCESS"
export const SEEN_CONVERSATIONS_FAIL = "SEEN_CONVERSATIONS_FAIL"

export const ACCEPTED_CONVERSATIONS_REQUEST = "ACCEPTED_CONVERSATIONS_REQUEST"
export const ACCEPTED_CONVERSATIONS_SUCCESS = "ACCEPTED_CONVERSATIONS_SUCCESS"
export const ACCEPTED_CONVERSATIONS_FAIL = "ACCEPTED_CONVERSATIONS_FAIL"

export const CREATE_CONVERSATIONS_REQUEST = "CREATE_CONVERSATIONS_REQUEST"
export const CREATE_CONVERSATIONS_SUCCESS = "CREATE_CONVERSATIONS_SUCCESS"
export const CREATE_CONVERSATIONS_FAIL = "CREATE_CONVERSATIONS_FAIL"
