export const CREATE_CONVERSATIONS_REQUEST = "CREATE_CONVERSATIONS_REQUEST"
export const CREATE_CONVERSATIONS_SUCCESS = "CREATE_CONVERSATIONS_SUCCESS"
export const CREATE_CONVERSATIONS_FAIL = "CREATE_CONVERSATIONS_FAIL"
