export const GET_ENTREPRISE_REQUEST = "GET_ENTREPRISE_REQUEST"
export const GET_ENTREPRISE_SUCCESS = "GET_ENTREPRISE_SUCCESS"
export const GET_ENTREPRISE_FAIL = "GET_ENTREPRISE_FAIL"

export const GET_CONSULTANT_REQUEST = "GET_CONSULTANT_REQUEST"
export const GET_CONSULTANT_SUCCESS = "GET_CONSULTANT_SUCCESS"
export const GET_CONSULTANT_FAIL = "GET_CONSULTANT_FAIL"

export const GET_INVESTOR_REQUEST = "GET_INVESTOR_REQUEST"
export const GET_INVESTOR_SUCCESS = "GET_INVESTOR_SUCCESS"
export const GET_INVESTOR_FAIL = "GET_INVESTOR_FAIL"
